- hosts: localhost
  connection: local

  vars:
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - homebrew/boneyard

    homebrew_cask_packages:
      - name: atom
      - name: rubymine
      - name: phpstorm
      - name: google-chrome
      - name: google-japanese-ime
      - name: firefox
      - name: slack
      - name: iterm2
      - name: bettertouchtool
      - name: sequel-pro
      - name: visual-studio-code

    homebrew_packages:
      - name: ansible
      - name: git
      - name: zsh
      - name: python
      - name: python3
      - name: rbenv
      - name: ruby-build
      - name: tmux
      - {name: yarn, install_options: without-node}
      - name: peco
      - name: jq
      - name: wget

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
        install_options: '{{ item.install_options | default() }}'
      with_items: '{{ homebrew_packages }}'

    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
